services:
  server:
    build: ./server
    container_name: brewease-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/app:z
      - /usr/src/app/node_modules
      - ./server/src/config/secrets/serviceAccountKey.json:/usr/src/app/src/config/secrets/serviceAccountKey.json:ro
    command: npm run dev

  client:
    build: ./client
    container_name: brewease-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app:z
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - server